### ISSUE TITLE
自动制卡时音频取不到

### ISSUE THREAD

**Issue by qingdaopijiudiaoge** [ninja33/ODH#36]
anki 2.0.52版本，ankiconnect6.0版本。之前是在群里下的anki 7合1绿色PC版，然后更新了上面两个的两个版本。

现在发现在在线划词字典已经设置好选项之后，自动制卡后audio字段取不到音频（选项中已经设置好音频对应audio字段）。其它的都可以取得到。

**Comment by ninja33** [comment]
可能是下载音频不成功。请问你用的哪本词典？

**Comment by qingdaopijiudiaoge** [comment]
我用哪本字典都取不到音频。不知道为什么？

**Comment by ninja33** [comment]
看了一下，下载音频确实有点问题。我平时因为不用下载的离线音频，都是用的模板里的在线音频，所以也没注意这个问题。

看看有空下一版改好他。

**Comment by Z-figaro** [comment]
me too ,怎么使用tts自动添加音频，或者直接使用一款内置音频？我也是开发，如果能分配一些工作。我乐意承担一部分开发工作

**Comment by ninja33** [comment]
tts自动添加音频的话，可以用anki的一款插件awesometts里添加。

至于上述的音频下载的问题，其实和插件没有关系，插件只是把音频地址传给了ankiconnect插件，实际音频文件是由ankiconnect下载的。唯一需要检查的是插件脚本产生的音频地址是否正确，所以需要知道是哪本词典

**Comment by Z-figaro** [comment]
我用的Collins英汉双解内置，我有两个问题：
1.我ankiconnect 打开了，但是在插件上死活都是未连接。从来没有连接上过。
2..audio img没有显示

我要去检查插件的脚本应该怎么检查Chrome app某一个控件呢？

**Comment by Z-figaro** [comment]
我检查了一下，只有audio字段拿不到

**Comment by 496147678** [comment]
同样的问题，制卡时音频提取不到，使用的是和楼主一样的版本。不知道什么时候可以出下一版。

Anki同时报错内容如下：

一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\......\Anki2\addons\AnkiConnect.py", line 359, in advance
    self.server.advance()
  File "C:\......\Anki2\addons\AnkiConnect.py", line 172, in advance
    self.advanceClients()
  File "C:\......\Anki2\addons\AnkiConnect.py", line 187, in advanceClients
    self.clients = filter(lambda c: c.advance(), self.clients)
  File "C:\......\Anki2\addons\AnkiConnect.py", line 187, in <lambda>
    self.clients = filter(lambda c: c.advance(), self.clients)
  File "C:\......\Anki2\addons\AnkiConnect.py", line 116, in advance
    self.writeBuff += self.handler(req)
  File "C:\......\Anki2\addons\AnkiConnect.py", line 201, in handlerWrapper
    body = json.dumps(self.handler(json.loads(req.body)))
  File "C:\......\Anki2\addons\AnkiConnect.py", line 365, in handler
    return getattr(self, action)(**(request.get('params') or {}))
  File "C:\Users\Xulei-Paul\AppData\Roaming\Anki2\addons\AnkiConnect.py", line 386, in api_addNote
    note.get('audio')
  File "C:\Users\Xulei-Paul\AppData\Roaming\Anki2\addons\AnkiConnect.py", line 248, in addNote
    data = audioDownload(audio['kana'], audio['kanji'])
KeyError: 'kana'
